import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { i18n } from "@/i18n.config";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sample App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.languages.map(({ locale }) => ({ lang: locale }));
}

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params?: { lang: string };
}>) {
  return (
    <html lang={params?.lang}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
